source 'https://rubygems.org'

gem 'asciidoctor-bespoke', '1.0.0.alpha.2'
gem 'coderay', '1.1.1'
# To use the latest version from git, use the following line instead
#gem 'asciidoctor-bespoke', github: 'asciidoctor/asciidoctor-bespoke'
