= <%= title %>
:uri-bespoke: http://markdalgleish.com/projects/bespoke.js
:uri-bundler: http://bundler.io
:uri-generator-bespoke: https://github.com/bespokejs/generator-bespoke
:uri-gulp: https://gulpjs.com
:uri-node: https://nodejs.org
:uri-nvm: https://github.com/creationix/nvm
:uri-ruby: https://www.ruby-lang.org
:uri-rvm: http://rvm.io

[quote]
A {uri-bespoke}[Bespoke.js] presentation generated by {uri-generator-bespoke}[generator-bespoke].

== View slides locally

First, ensure you have the following installed:

. {uri-node}[Node.js] footnote:[We strongly recommend using {uri-nvm}[nvm] to manage Node.]
. {uri-gulp}[Gulp] (command line interface only)

 $ npm install -g gulp-cli

<% if (useAsciiDoc) { -%>
. {uri-ruby}[Ruby >= 2] footnote:[We strongly recommend using {uri-rvm}[RVM] to manage Ruby.]

 $ rvm use 2.4.2 --install

. {uri-bundler}[Bundler]

 $ gem install bundler
<% } -%>

Next, install dependencies (if you ran the generator with the `--skip-install` switch):

 $ npm install
<% if (useAsciiDoc) { -%>
   bundle --path=.bundle/gems
<% } -%>

Finally, build and serve the presentation!

 $ gulp serve

You can view the presentation in your browser at the URL displayed in the console.

To build the presentation without starting the local preview server, use:

 $ gulp

In both cases, the files are built into the [.path]_dist_ directory.
You can view the slides outside of the local preview server by navigating to [.path]_dist/index.html_ in your browser.

== Publish to GitHub Pages

The Gulp build includes a task to publish your presentation to GitHub Pages.

First, make sure you have initialized the project as a git repository and linked it to a GitHub project.
The task assumes that the git remote named `origin` points to the repository on GitHub.

Now you can build the presentation and publish it to GitHub Pages using:

 $ gulp publish

The files in the [.path]_dist_ directory end up in the `gh-pages` branch in the repository on GitHub.
From there, they can be viewed in a browser from anywhere on the web.
